# Generated by Django 4.2.3 on 2023-11-18 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities_address', models.CharField(help_text='facilities_address', max_length=500, null=True, verbose_name='facilities_address')),
                ('facilities_type', models.CharField(help_text='facilities_type', max_length=255, null=True, verbose_name='facilities_type')),
                ('facilities_lat', models.DecimalField(decimal_places=6, help_text='facilities_lat', max_digits=9, null=True, verbose_name='facilities_lat')),
                ('facilities_long', models.DecimalField(decimal_places=6, help_text='facilities_long', max_digits=9, null=True, verbose_name='facilities_long')),
                ('facilites_rspo', models.CharField(help_text='facilites_rspo', max_length=255, null=True, verbose_name='facilites_rspo')),
                ('facilites_date_update', models.CharField(help_text='facilites_date_update', max_length=255, null=True, verbose_name='facilites_date_update')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
