# Generated by Django 4.2.3 on 2023-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facilities_eq_id',
            field=models.CharField(help_text='facilities_eq_id', max_length=255, null=True, verbose_name='facilities_eq_id'),
        ),
    ]
