# Generated by Django 4.2.3 on 2023-11-19 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facility_facilities_eq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refinery_eq_id', models.CharField(help_text='refinery_eq_id', max_length=255, null=True, verbose_name='refinery_eq_id')),
                ('refinery_address', models.CharField(help_text='refinery_address', max_length=500, null=True, verbose_name='refinery_address')),
                ('refinery_type', models.CharField(help_text='refinery_type', max_length=255, null=True, verbose_name='refinery_type')),
                ('refinery_lat', models.DecimalField(decimal_places=6, help_text='refinery_lat', max_digits=9, null=True, verbose_name='refinery_lat')),
                ('refinery_long', models.DecimalField(decimal_places=6, help_text='refinery_long', max_digits=9, null=True, verbose_name='refinery_long')),
                ('refinery_rspo', models.CharField(help_text='refinery_rspo', max_length=255, null=True, verbose_name='refinery_rspo')),
                ('refinery_date_update', models.CharField(help_text='refinery_date_update', max_length=255, null=True, verbose_name='refinery_date_update')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Refinery',
                'verbose_name_plural': 'Refineries',
            },
        ),
    ]
