# Generated by Django 4.2.3 on 2023-11-19 08:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_facility_facilities_name_refinery_refinery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mill_company_name', models.CharField(help_text='mill_company_name', max_length=255, null=True, verbose_name='mill_company_name')),
                ('mill_company_group_id', models.CharField(help_text='mill_company_group_id', max_length=255, null=True, verbose_name='mill_company_group_id')),
                ('mill_company_group', models.CharField(help_text='mill_company_group', max_length=255, null=True, verbose_name='mill_company_group')),
                ('mill_country', models.CharField(help_text='mill_country', max_length=255, null=True, verbose_name='mill_country')),
                ('mill_province', models.CharField(help_text='mill_province', max_length=255, null=True, verbose_name='mill_province')),
                ('mill_district', models.CharField(help_text='mill_district', max_length=255, null=True, verbose_name='mill_district')),
                ('mill_address', models.CharField(help_text='mill_address', max_length=500, null=True, verbose_name='mill_address')),
                ('mill_type', models.CharField(help_text='mill_type', max_length=255, null=True, verbose_name='mill_type')),
                ('mill_lat', models.DecimalField(decimal_places=6, help_text='mill_lat', max_digits=9, null=True, verbose_name='mill_lat')),
                ('mill_long', models.DecimalField(decimal_places=6, help_text='mill_long', max_digits=9, null=True, verbose_name='mill_long')),
                ('mill_rspo', models.CharField(help_text='mill_rspo', max_length=255, null=True, verbose_name='mill_rspo')),
                ('mill_mspo', models.CharField(help_text='mill_mspo', max_length=255, null=True, verbose_name='mill_mspo')),
                ('mill_capacity', models.CharField(help_text='mill_capacity', max_length=255, null=True, verbose_name='mill_capacity')),
                ('mill_methane_capture', models.CharField(help_text='mill_methane_capture', max_length=255, null=True, verbose_name='mill_methane_capture')),
                ('mill_deforestation_risk', models.CharField(help_text='mill_deforestation_risk', max_length=255, null=True, verbose_name='mill_deforestation_risk')),
                ('mill_legal_prf_risk', models.CharField(help_text='mill_legal_prf_risk', max_length=255, null=True, verbose_name='mill_legal_prf_risk')),
                ('mill_legal_production_forest', models.CharField(help_text='mill_legal_production_forest', max_length=255, null=True, verbose_name='mill_legal_production_forest')),
                ('mill_legal_conservation_area', models.CharField(help_text='mill_legal_conservation_area', max_length=255, null=True, verbose_name='mill_legal_conservation_area')),
                ('mill_legal_landuse_risk', models.CharField(help_text='mill_legal_landuse_risk', max_length=255, null=True, verbose_name='mill_legal_landuse_risk')),
                ('mill_complex_supplybase_risk', models.CharField(help_text='mill_complex_supplybase_risk', max_length=255, null=True, verbose_name='mill_complex_supplybase_risk')),
                ('mill_date_update', models.CharField(help_text='mill_date_update', max_length=255, null=True, verbose_name='mill_date_update')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mill',
                'verbose_name_plural': 'Mills',
            },
        ),
    ]
