# Generated by Django 4.2.3 on 2023-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agriplot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriplot',
            name='Planted_Ar',
            field=models.CharField(help_text='Planted_Ar', max_length=255, null=True, verbose_name='Planted_Ar'),
        ),
    ]
