# Generated by Django 4.2.3 on 2023-11-19 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_agriplot_planted_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracetomill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_eq_id', models.CharField(help_text='facility_eq_id', max_length=255, null=True, verbose_name='facility_eq_id')),
                ('mill_eq_id', models.CharField(help_text='mill_eq_id', max_length=255, null=True, verbose_name='mill_eq_id')),
                ('mill_uml_id', models.CharField(help_text='mill_uml_id', max_length=255, null=True, verbose_name='mill_uml_id')),
                ('mill_name', models.CharField(help_text='mill_name', max_length=255, null=True, verbose_name='mill_name')),
                ('ttm_source_type', models.CharField(help_text='ttm_source_type', max_length=255, null=True, verbose_name='ttm_source_type')),
                ('ttm_year_period', models.CharField(help_text='ttm_year_period', max_length=255, null=True, verbose_name='ttm_year_period')),
                ('ttm_date_update', models.CharField(help_text='ttm_date_update', max_length=255, null=True, verbose_name='ttm_date_update')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tracetomill',
                'verbose_name_plural': 'Tracetomills',
            },
        ),
    ]
