# Generated by Django 4.2.3 on 2023-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tracetoplantation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriplot',
            name='ID_Mill',
        ),
        migrations.RemoveField(
            model_name='agriplot',
            name='Mill_Name',
        ),
        migrations.AddField(
            model_name='facility',
            name='facilities_country',
            field=models.CharField(help_text='refinery_country', max_length=500, null=True, verbose_name='refinery_country'),
        ),
        migrations.AddField(
            model_name='refinery',
            name='refinery_country',
            field=models.CharField(help_text='refinery_country', max_length=500, null=True, verbose_name='refinery_country'),
        ),
    ]
