# Generated by Django 4.2.3 on 2023-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_agriplot_id_mill_remove_agriplot_mill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='ID_Mill',
            field=models.CharField(help_text='ID_Mill', max_length=255, null=True, verbose_name='ID_Mill'),
        ),
        migrations.AddField(
            model_name='agriplot',
            name='Mill_Name',
            field=models.CharField(help_text='Mill_Name', max_length=255, null=True, verbose_name='Mill_Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facilities_country',
            field=models.CharField(help_text='facilities_country', max_length=500, null=True, verbose_name='facilities_country'),
        ),
    ]
