# Generated by Django 4.2.3 on 2023-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_agriplot_id_mill_agriplot_mill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='Status',
            field=models.CharField(help_text='Status', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
