# Generated by Django 4.2.3 on 2023-11-21 17:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_agriplot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantedOutsideLandRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mukim', models.CharField(help_text='Mukim', max_length=255, null=True, verbose_name='Mukim')),
                ('ID_Mukim', models.CharField(help_text='ID_Mukim', max_length=255, null=True, verbose_name='ID_Mukim')),
                ('Daerah', models.CharField(help_text='Daerah', max_length=255, null=True, verbose_name='Daerah')),
                ('ID_Daerah', models.CharField(help_text='ID_Daerah', max_length=255, null=True, verbose_name='ID_Daerah')),
                ('Negeri', models.CharField(help_text='Negeri', max_length=255, null=True, verbose_name='Negeri')),
                ('ID_Negeri', models.CharField(help_text='ID_Negeri', max_length=255, null=True, verbose_name='ID_Negeri')),
                ('Country', models.CharField(help_text='Country', max_length=255, null=True, verbose_name='Country')),
                ('Note', models.CharField(help_text='Note', max_length=255, null=True, verbose_name='Note')),
                ('ttp_source_type', models.CharField(help_text='ttp_source_type', max_length=255, null=True, verbose_name='ttp_source_type')),
                ('Status', models.CharField(help_text='Status', max_length=255, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, null=True, srid=4326)),
                ('is_display', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
