# Generated by Django 4.2.3 on 2023-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_plantedoutsidelandregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='actual_supplier',
            field=models.BooleanField(default=True),
        ),
    ]
