# Generated by Django 4.2.3 on 2023-11-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_agriplot_actual_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantedoutsidelandregistration',
            options={'verbose_name': 'PlantedOutsideLandRegistration', 'verbose_name_plural': 'PlantedOutsideLandRegistrations'},
        ),
    ]
