# Generated by Django 4.2.3 on 2023-11-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_plantedoutsidelandregistration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedoutsidelandregistration',
            name='ttp_source_type',
        ),
    ]
