# Generated by Django 4.2.3 on 2023-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_agriplot_id_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='id_estate',
            field=models.CharField(help_text='id_estate', max_length=255, null=True, verbose_name='id_estate'),
        ),
    ]
