# Generated by Django 4.2.3 on 2023-11-25 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_plantedoutsidelandregistration_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedoutsidelandregistration',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
