# Generated by Django 4.2.3 on 2023-11-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_agriplot_agriplotid_remove_agriplot_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agriplot',
            old_name='ownership',
            new_name='ownership_plot',
        ),
        migrations.RenameField(
            model_name='agriplot',
            old_name='status',
            new_name='status_plot',
        ),
        migrations.RenameField(
            model_name='plantedoutsidelandregistration',
            old_name='status',
            new_name='status_plot',
        ),
    ]
