# Generated by Django 4.2.3 on 2023-12-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_ownership_agriplot_ownership_plot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='mill_eq_id',
            field=models.CharField(help_text='mill_eq_id', max_length=255, null=True, verbose_name='mill_eq_id'),
        ),
    ]
