# Generated by Django 4.2.3 on 2023-12-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_agriplot_mill_eq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriplot',
            name='mill_eq_id',
        ),
        migrations.AddField(
            model_name='agriplot',
            name='millideq',
            field=models.CharField(help_text='millideq', max_length=255, null=True, verbose_name='mill_eq_id'),
        ),
    ]
