# Generated by Django 4.2.3 on 2023-12-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_agriplot_mill_eq_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantedOutsideLandRegistration',
        ),
    ]
