# Generated by Django 4.2.3 on 2023-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_plantedoutsidelandregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriplot',
            name='status_plot',
        ),
        migrations.AddField(
            model_name='agriplot',
            name='status_of_plot',
            field=models.CharField(help_text='status_of_plot', max_length=255, null=True, verbose_name='status_of_plot'),
        ),
    ]
