# Generated by Django 4.2.3 on 2024-01-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_agriplot_status_plot_agriplot_status_of_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='is_planted',
            field=models.BooleanField(default=False),
        ),
    ]
