# Generated by Django 4.2.3 on 2024-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_mill_is_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriplot',
            name='compliance',
            field=models.CharField(help_text='compliance', max_length=255, null=True, verbose_name='compliance'),
        ),
        migrations.AddField(
            model_name='agriplot',
            name='def_free',
            field=models.CharField(help_text='def_free', max_length=255, null=True, verbose_name='def_free'),
        ),
    ]
