# Generated by Django 4.2.3 on 2024-01-15 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_agriplot_compliance_agriplot_def_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, db_index=True, dim=3, null=True, srid=4326),
        ),
    ]
