# Generated by Django 4.2.3 on 2024-02-18 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_agriplot_compliance_agriplot_def_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAgriplot',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ownership', models.TextField(blank=True, db_column='ownership', null=True)),
                ('subsidiary', models.TextField(blank=True, db_column='subsidiary', null=True)),
                ('estate', models.TextField(blank=True, db_column='estate', null=True)),
                ('id_estate', models.TextField(blank=True, db_column='id_estate', null=True)),
                ('agriplotid', models.TextField(blank=True, db_column='agriplotid', null=True)),
                ('typeofsupp', models.TextField(blank=True, db_column='typeofsupp', null=True)),
                ('village', models.TextField(blank=True, db_column='village', null=True)),
                ('subdistric', models.TextField(blank=True, db_column='subdistric', null=True)),
                ('district', models.TextField(blank=True, db_column='district', null=True)),
                ('province', models.TextField(blank=True, db_column='province', null=True)),
                ('country', models.TextField(blank=True, db_column='country', null=True)),
                ('planted_ar', models.FloatField(blank=True, db_column='planted_ar', null=True)),
                ('yearupdate', models.TextField(blank=True, db_column='yearupdate', null=True)),
                ('riskassess', models.TextField(blank=True, db_column='riskassess', null=True)),
                ('ghg_luc', models.TextField(blank=True, db_column='ghg_luc', null=True)),
                ('luas', models.FloatField(blank=True, db_column='luas', null=True)),
                ('shape_leng', models.FloatField(blank=True, db_column='shape_leng', null=True)),
                ('shape_area', models.FloatField(blank=True, db_column='shape_area', null=True)),
                ('mill_eq_id', models.TextField(blank=True, null=True)),
                ('def_free', models.TextField(blank=True, db_column='def_free', null=True)),
                ('compliance', models.TextField(blank=True, db_column='compliance', null=True)),
                ('legal_comp', models.TextField(blank=True, db_column='legal_comp', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geometry', null=True, srid=4326)),
            ],
            options={
                'db_table': 'test_agriplot',
                'managed': False,
            },
        ),
    ]
