# Generated by Django 4.2.3 on 2024-01-31 13:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_agriplot_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAgriplot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.TextField(blank=True, db_column='Ownership', null=True)),
                ('subsidiary', models.TextField(blank=True, db_column='Subsidiary', null=True)),
                ('estate', models.TextField(blank=True, db_column='Estate', null=True)),
                ('id_estate', models.TextField(blank=True, db_column='ID_Estate', null=True)),
                ('agriplotid', models.TextField(blank=True, db_column='AgriplotID', null=True)),
                ('typeofsupp', models.TextField(blank=True, db_column='TypeOfSupp', null=True)),
                ('village', models.TextField(blank=True, db_column='Village', null=True)),
                ('subdistric', models.TextField(blank=True, db_column='SubDistric', null=True)),
                ('district', models.TextField(blank=True, db_column='District', null=True)),
                ('province', models.TextField(blank=True, db_column='Province', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('planted_ar', models.FloatField(blank=True, db_column='Planted_Ar', null=True)),
                ('yearupdate', models.TextField(blank=True, db_column='YearUpdate', null=True)),
                ('riskassess', models.TextField(blank=True, db_column='RiskAssess', null=True)),
                ('ghg_luc', models.TextField(blank=True, db_column='GHG_LUC', null=True)),
                ('luas', models.FloatField(blank=True, db_column='Luas', null=True)),
                ('shape_leng', models.FloatField(blank=True, db_column='Shape_Leng', null=True)),
                ('shape_area', models.FloatField(blank=True, db_column='Shape_Area', null=True)),
                ('mill_eq_id', models.TextField(blank=True, null=True)),
                ('def_free', models.TextField(blank=True, db_column='Def_Free', null=True)),
                ('compliance', models.TextField(blank=True, db_column='Compliance', null=True)),
                ('legal_comp', models.TextField(blank=True, db_column='Legal_Comp', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'test_agriplot',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='agriplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
