# Generated by Django 4.2.3 on 2024-01-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_testagriplot_alter_agriplot_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAgriplot',
        ),
    ]
